name: DimeClient
version: 0.0.1
author: Till WegmÃ¼ller
description: A WebApp Client for DimeErp
homepage: http://github.com/stiftungswo/Dime
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular: "^5.0.0-alpha+12"
  angular_router: "^2.0.0-alpha+11"
  angular_forms: "^2.0.0-alpha+4"
  pikaday: "^1.2.0"
  #pikaday_datepicker_angular: "^3.1.0" todo remove our custom version and use this as soon as it supports angular5
  hammock:
    git:
        url: https://github.com/stiftungswo/hammock.git
        ref: 0.7.0-alpha
  sentry_client: ">=4.0.3 < 5.0.0"
  meta: ^1.1.2
  stack_trace: "^1.9.2"
  markdown: "^2.0.0"

dev_dependencies:
  build_runner: "^0.8.9"
  build_test: "^0.10.2+3"
  build_web_compilers: "^0.4.0+1"

